#!/usr/bin/env python3
"""Regenerate specs/TRACEABILITY.md — the spec ↔ source-testcase map.

Joins the specs on disk with `testcase-classification.csv` (its `spec_id` column is the
system of record) and writes one table per area: each spec, its title, and the source
case(s) it was derived from (src #, section/functionality, oracle). Specs with no source
row (split scenarios / derived beyond the source set) are listed separately, with the
prose `source:` from their own front-matter.

Usage:
    python .github/scripts/generate_traceability.py          # rewrite the file
    python .github/scripts/generate_traceability.py --check   # exit 1 if stale
"""
from __future__ import annotations

import csv
import collections
import re
import sys
from pathlib import Path

from _common import AREA_PREFIX, id_from_stem, order_key, display_name

REPO = Path(__file__).resolve().parents[2]
SPECS = REPO / "specs"
CSV = REPO / "testcase-classification.csv"
OUT = REPO / "TRACEABILITY.md"


def front_matter(text: str, key: str) -> str:
    m = re.search(rf"(?m)^{key}:\s*(.*)$", text.split("---", 2)[1] if text.startswith("---") else "")
    if not m:
        return ""
    v = m.group(1).strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
        v = v[1:-1]
    return v


def render() -> str:
    rows = list(csv.DictReader(CSV.open(encoding="utf-8")))
    by_spec: dict[str, list[dict]] = collections.defaultdict(list)
    for r in rows:
        if r.get("spec_id"):
            by_spec[r["spec_id"]].append(r)

    # collect specs on disk, grouped by area
    by_area: dict[str, list[tuple[str, Path]]] = collections.defaultdict(list)
    for md in SPECS.rglob("*.md"):
        if md.name in ("index.md", "TRACEABILITY.md"):
            continue
        area = md.parent.relative_to(SPECS).as_posix()
        by_area[area].append((id_from_stem(md.stem), md))

    total = sum(len(v) for v in by_area.values())
    mapped = sum(1 for _, mds in by_area.items() for sid, _ in mds if sid in by_spec)
    lines = [
        "# Spec ↔ testcase traceability",
        "",
        "Generated by `.github/scripts/generate_traceability.py` — do not edit by hand.",
        f"Maps each spec to its source case(s) in "
        f"[`testcase-classification.csv`](testcase-classification.csv).",
        "",
        f"**{total}** specs · **{mapped}** with a source row · **{total - mapped}** without "
        f"(see *Specs with no source row* at the end). Run "
        f"`python .github/scripts/trace.py <ID>` for the full source detail.",
        "",
    ]

    gaps: list[tuple[str, Path]] = []
    for area in sorted(by_area, key=order_key):
        specs = sorted(by_area[area], key=lambda t: t[0])
        lines += [f"## {display_name(area.split('/')[-1])}  (`{area}`)", ""]
        lines += ["| spec | title | source src# | source functionality | oracle |",
                  "|------|-------|-------------|----------------------|--------|"]
        for sid, md in specs:
            title = front_matter(md.read_text(), "title")
            srcs = by_spec.get(sid, [])
            if not srcs:
                gaps.append((sid, md))
                lines.append(f"| {sid} | {title} | — | — | — |")
                continue
            src_ids = ", ".join(s["src"] for s in srcs)
            func = " · ".join(
                " / ".join(x for x in (s.get("section"), s.get("functionality")) if x)
                for s in srcs
            )
            oracle = ", ".join(sorted({s.get("oracle", "") for s in srcs}))
            lines.append(f"| {sid} | {title} | {src_ids} | {func} | {oracle} |")
        lines.append("")

    lines += ["## Specs with no source row", ""]
    if gaps:
        lines += ["These were split from a multi-scenario flow or derived beyond the source "
                  "set; provenance is the prose `source:` in their own front-matter.", ""]
        lines += ["| spec | title | front-matter source |",
                  "|------|-------|----------------------|"]
        for sid, md in sorted(gaps):
            txt = md.read_text()
            lines.append(f"| {sid} | {front_matter(txt,'title')} | {front_matter(txt,'source')} |")
    else:
        lines.append("_None — every spec maps to at least one source case._")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv[1:]
    content = render()
    current = OUT.read_text() if OUT.exists() else None
    if current == content:
        print("TRACEABILITY.md is up to date.")
        return 0
    if check:
        print("TRACEABILITY.md is stale (run generate_traceability.py).", file=sys.stderr)
        return 1
    OUT.write_text(content)
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
